library(ggplot2)
realState <- read_xlsx("realState.xlsx", )
View(realState)

#factoring
realState$`Host Id`<-as.factor(realState$`Host Id`)
realState$`Host Since`<-as.factor(realState$`Host Since`)
realState$Name<-as.factor(realState$Name)
realState$Neighbourhood<-as.factor(realState$Neighbourhood)
realState$`Property Type`<-as.factor(realState$`Property Type`)
realState$`Review Scores Rating (bin)`<-as.factor(realState$`Review Scores Rating (bin)`)
realState$`Room Type`<-as.factor(realState$`Room Type`)
realState$Zipcode<-as.factor(realState$Zipcode)
realState$Beds<-as.factor(realState$Beds)
realState$`Number of Records`<-as.factor(realState$`Number of Records`)
realState$`Number Of Reviews`<-as.factor(realState$`Number Of Reviews`)
realState$Price<-as.factor(realState$Price)
realState$`Review Scores Rating`<-as.factor(realState$`Review Scores Rating`)

summary(realState)
mean(realState$Price)
mean(realState$`Review Scores Rating`)
sd(realState$Price)
sd(realState$`Review Scores Rating`)
hist(realState$Neighborhood)
hist(realState$Price)

plot(realState$Price~realState$`Number Of Reviews`,ylab="Price",xlab="Review",main="Price Vs Review")
hist(realState$`Review Scores Rating (bin)`, xlab = "Review Score", ylab = "Number of Properties", col = "aquamarine", main = "Review Variation in the Properties")
boxplot(realState$Price~realState$Neighborhood)

#ggplot
library(ggplot2)
ggplot(data=realState)
ggplot(data=realState, aes(x=Price, y=`Review Scores Rating (bin)`))
ggplot(data=realState, aes(x=Price, y=`Review Scores Rating (bin)`))+geom_point()
ggplot(data=realState, aes(x=Price, y=`Review Scores Rating (bin)`, col=Neighborhood))+geom_point()
ggplot(data=realState, aes(x=Price, y=`Review Scores Rating (bin)`, shape=Neighborhood))+geom_point()
ggplot(data=realState, aes(x=Price, y=`Review Scores Rating (bin)`, shape=Neighborhood, col=Neighborhood))+geom_point()
ggplot(data=realState, aes(x=Price, col=Neighborhood))+geom_freqpoly(bins=50000)


ggplot(data=realState, aes(x=factor(Beds), y=Price))+geom_boxplot()
ggplot(data=realState, aes(x=factor(Beds), y=Price, fill=factor(Neighborhood)))+geom_boxplot()
table(realState$`Review Scores Rating`)
cor(realState$`Review Scores Rating (bin)`, realState$Price)
