library(ggplot2)
realState <- read_xlsx("realState.xlsx", )
View(realState)

#factoring
realState$`Host Id`<-as.factor(realState$`Host Id`)
realState$`Host Since`<-as.factor(realState$`Host Since`)
realState$Name<-as.factor(realState$Name)
realState$Neighbourhood<-as.factor(realState$Neighbourhood)
realState$`Property Type`<-as.factor(realState$`Property Type`)
realState$`Review Scores Rating (bin)`<-as.factor(realState$`Review Scores Rating (bin)`)
realState$`Room Type`<-as.factor(realState$`Room Type`)
realState$Zipcode<-as.factor(realState$Zipcode)
realState$Beds<-as.factor(realState$Beds)
realState$`Number of Records`<-as.factor(realState$`Number of Records`)
realState$`Number Of Reviews`<-as.factor(realState$`Number Of Reviews`)
realState$Price<-as.factor(realState$Price)
realState$`Review Scores Rating`<-as.factor(realState$`Review Scores Rating`)

summary(realState)
mean(realState$Price)
mean(realState$`Review Scores Rating`)
sd(realState$Price)
sd(realState$`Review Scores Rating`)
hist(realState$Neighborhood)
hist(realState$Price)
